using System;
using System.Collections.Generic;
using System.Reflection;
using HarmonyLib;
using TaleWorlds.CampaignSystem;
using TaleWorlds.Localization;

namespace BellumCivile.Patches
{
    [HarmonyPatch]
    internal static class DynamicKingdomTitleNamePatch
    {
        [HarmonyPatch(typeof(Kingdom), nameof(Kingdom.Name), MethodType.Getter)]
        [HarmonyPostfix]
        [HarmonyPriority(Priority.Last)]
        private static void NamePostfix(Kingdom __instance, ref TextObject __result)
        {
            __result = DynamicKingdomTitleNameHelper.ResolveNameRead(
                __instance,
                __result,
                KingdomDisplayNameField.Name);
        }

        [HarmonyPatch(typeof(Kingdom), nameof(Kingdom.EncyclopediaTitle), MethodType.Getter)]
        [HarmonyPostfix]
        [HarmonyPriority(Priority.Last)]
        private static void EncyclopediaTitlePostfix(Kingdom __instance, ref TextObject __result)
        {
            __result = DynamicKingdomTitleNameHelper.ResolveNameRead(
                __instance,
                __result,
                KingdomDisplayNameField.EncyclopediaTitle);
        }

        [HarmonyPatch(typeof(Kingdom), nameof(Kingdom.ChangeKingdomName))]
        [HarmonyPostfix]
        private static void ChangeKingdomNamePostfix(
            Kingdom __instance,
            TextObject name,
            TextObject informalName)
        {
            DynamicKingdomTitleNameHelper.RecordNativeNameChange(__instance, name, informalName);
        }

        [HarmonyPatch(typeof(Kingdom), nameof(Kingdom.InitializeKingdom))]
        [HarmonyPostfix]
        private static void InitializeKingdomPostfix(
            Kingdom __instance,
            TextObject name,
            TextObject informalName,
            TextObject encyclopediaTitle)
        {
            DynamicKingdomTitleNameHelper.RecordNativeInitialization(
                __instance,
                name,
                informalName,
                encyclopediaTitle);
        }
    }

    [HarmonyPatch]
    internal static class DynamicKingdomTitleNameSaveBoundaryPatch
    {
        private static IEnumerable<MethodBase> TargetMethods()
        {
            MethodInfo collector = AccessTools.DeclaredMethod(
                typeof(Kingdom),
                "AutoGeneratedInstanceCollectObjects");
            MethodInfo nameGetter = AccessTools.DeclaredMethod(
                typeof(Kingdom),
                "AutoGeneratedGetMemberValueName");
            MethodInfo encyclopediaTitleGetter = AccessTools.DeclaredMethod(
                typeof(Kingdom),
                "AutoGeneratedGetMemberValueEncyclopediaTitle");

            if (collector != null)
                yield return collector;
            if (nameGetter != null)
                yield return nameGetter;
            if (encyclopediaTitleGetter != null)
                yield return encyclopediaTitleGetter;
        }

        [HarmonyPrefix]
        private static void Prefix(out IDisposable __state)
        {
            __state = DynamicKingdomTitleNameHelper.BeginNativeNameReadScope();
        }

        [HarmonyFinalizer]
        private static Exception Finalizer(Exception __exception, IDisposable __state)
        {
            __state?.Dispose();
            return __exception;
        }
    }
}
