$ErrorActionPreference = 'Stop'
$root = Split-Path $PSScriptRoot -Parent
function Read($path) { Get-Content -Raw (Join-Path $root $path) }
function Check($condition, $message) { if (!$condition) { throw $message }; "PASS: $message" }
$rivalry = Read 'Behaviors/CivilWarRivalry.cs'
$settle = Read 'Behaviors/CivilWarRivalSettlement.cs'
$score = Read 'Behaviors/WarScoreBehavior.cs'
$recovery = Read 'Behaviors/CivilWarSuccessionSettlement.cs'
$save = Read 'BellumCivileSaveDefiner.cs'
Check ($rivalry -notmatch 'DeclareWar|CreateKingdom|TriggerUltimatum') 'Rival-pair registration observes existing hostility; it does not activate a new war.'
Check ($score.Contains('TryResolveRivalVictory(war, primaryVictory)') -and $score.Contains('faction.ParentKingdom != opposing')) 'Rival scores cannot accidentally install a claimant through the ordinary Crown-victory resolver.'
Check ($score.Contains('if (CivilWarConflictBehavior.IsRivalryScore(war)) return false;')) 'Generic internal white peace cannot settle a whole claimant coalition for a rivalry pairing.'
Check ($settle.Contains('winner.Faction.MoveClanToKingdomPreservingCivilWarInfluence(clan, winner.Realm') -and $settle.Contains('winner.Faction.AddMember(clan)')) 'Surviving defeated houses enter the victorious claimant realm and existing coalition.'
Check ($settle.Contains('TryQueueChallengeTribunal(loser.Faction, winner.Realm)') -and $settle.Contains('QueuePlayerTribunal(winner.Realm, winner.Realm, record.LosingClans')) 'Victorious claimant judges only the defeated coalition through the shared tribunal path.'
Check ($settle.Contains('CompleteCivilWarTracker(loser.Faction, loser.Realm') -and $settle -notmatch 'CompleteCivilWarTracker\(winner') 'Settlement closes the losing claimant, not the victor ongoing Crown war.'
Check ($settle -notmatch 'AddBattleScore|AddTickingScore|SetOccupationScore|TrySetKingdomTitleRuler|MarkAsUsurper|TriggerUltimatum|CreateKingdom') 'Rival absorption neither combines scores nor awards the Crown nor restarts the rebellion.'
Check ($rivalry -match '_rivalDefeats.Add\(record\);\s*ResumeRivalDefeat\(record\);') 'Rival settlement records its winner, losers and destination before mutation.'
Check ($recovery.IndexOf('TryResumeRivalChallengeOutcome(record)') -lt $recovery.IndexOf('realm = CreateRestoredSuccessorKingdom')) 'Hereditary loser recovery delegates to its saved absorption owner.'
Check ((Read 'Behaviors/SuccessionChallengeWar.cs').Contains('OwnsRivalDefeat(ownedRivalDefeat)') -and $settle.Contains('SuccessionChallengeOutcome.Defeat, winner.Realm, record')) 'Owned hereditary restitution uses a validated saved settlement rather than a blanket protection bypass.'
Check ($settle.Contains('record.RewardedClans') -and $settle.Contains('if (!record.TribunalQueued)')) 'Reward and tribunal receipts survive retry.'
Check ($save.Contains('AddClassDefinition(typeof(CivilWarRivalDefeatRecord), 87)') -and $save.Contains('ConstructContainerDefinition(typeof(List<CivilWarRivalDefeatRecord>))')) 'Rival absorption journal is registered for persistence.'
Check ((Read 'Behaviors/ElectiveContestDispatch.cs').Contains('!StartRivalry(record,')) 'Dual claimant dispatch registers the rivalry before startup completes.'
[xml]$strings = Read 'ModuleData/Languages/EN/strings.xml'
Check (@($strings.base.strings.string | Where-Object id -eq 'BC_CivilWar_RivalAbsorbed').Count -eq 1) 'Rival-absorption notification is localized exactly once.'
'Source contracts only; native transfers, tribunals and save/load still need campaign testing.'
